name: flutter_golden_test_alchemist
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  alchemist: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: WarrenDisplay
      fonts:
        - asset: assets/fonts/WarrenDisplay-Regular.otf
        - asset: assets/fonts/WarrenDisplay-Bold.otf
          weight: 700
